# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taggedobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tag.TaggedObject')),
                ('name', models.CharField(default='Task', max_length=256)),
                ('description', models.TextField(default='')),
            ],
            bases=('tag.taggedobject',),
        ),
    ]
